package com.yunbiao.yb_smart_meeting.db2;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yunbiao.yb_smart_meeting.db2.AdvertInfo;
import com.yunbiao.yb_smart_meeting.db2.DepartBean;
import com.yunbiao.yb_smart_meeting.db2.EntryInfo;
import com.yunbiao.yb_smart_meeting.db2.FlowInfo;
import com.yunbiao.yb_smart_meeting.db2.MeetInfo;
import com.yunbiao.yb_smart_meeting.db2.PassageBean;
import com.yunbiao.yb_smart_meeting.db2.UserBean;
import com.yunbiao.yb_smart_meeting.db2.VisitorBean;

import com.yunbiao.yb_smart_meeting.db2.AdvertInfoDao;
import com.yunbiao.yb_smart_meeting.db2.DepartBeanDao;
import com.yunbiao.yb_smart_meeting.db2.EntryInfoDao;
import com.yunbiao.yb_smart_meeting.db2.FlowInfoDao;
import com.yunbiao.yb_smart_meeting.db2.MeetInfoDao;
import com.yunbiao.yb_smart_meeting.db2.PassageBeanDao;
import com.yunbiao.yb_smart_meeting.db2.UserBeanDao;
import com.yunbiao.yb_smart_meeting.db2.VisitorBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig advertInfoDaoConfig;
    private final DaoConfig departBeanDaoConfig;
    private final DaoConfig entryInfoDaoConfig;
    private final DaoConfig flowInfoDaoConfig;
    private final DaoConfig meetInfoDaoConfig;
    private final DaoConfig passageBeanDaoConfig;
    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig visitorBeanDaoConfig;

    private final AdvertInfoDao advertInfoDao;
    private final DepartBeanDao departBeanDao;
    private final EntryInfoDao entryInfoDao;
    private final FlowInfoDao flowInfoDao;
    private final MeetInfoDao meetInfoDao;
    private final PassageBeanDao passageBeanDao;
    private final UserBeanDao userBeanDao;
    private final VisitorBeanDao visitorBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        advertInfoDaoConfig = daoConfigMap.get(AdvertInfoDao.class).clone();
        advertInfoDaoConfig.initIdentityScope(type);

        departBeanDaoConfig = daoConfigMap.get(DepartBeanDao.class).clone();
        departBeanDaoConfig.initIdentityScope(type);

        entryInfoDaoConfig = daoConfigMap.get(EntryInfoDao.class).clone();
        entryInfoDaoConfig.initIdentityScope(type);

        flowInfoDaoConfig = daoConfigMap.get(FlowInfoDao.class).clone();
        flowInfoDaoConfig.initIdentityScope(type);

        meetInfoDaoConfig = daoConfigMap.get(MeetInfoDao.class).clone();
        meetInfoDaoConfig.initIdentityScope(type);

        passageBeanDaoConfig = daoConfigMap.get(PassageBeanDao.class).clone();
        passageBeanDaoConfig.initIdentityScope(type);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        visitorBeanDaoConfig = daoConfigMap.get(VisitorBeanDao.class).clone();
        visitorBeanDaoConfig.initIdentityScope(type);

        advertInfoDao = new AdvertInfoDao(advertInfoDaoConfig, this);
        departBeanDao = new DepartBeanDao(departBeanDaoConfig, this);
        entryInfoDao = new EntryInfoDao(entryInfoDaoConfig, this);
        flowInfoDao = new FlowInfoDao(flowInfoDaoConfig, this);
        meetInfoDao = new MeetInfoDao(meetInfoDaoConfig, this);
        passageBeanDao = new PassageBeanDao(passageBeanDaoConfig, this);
        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        visitorBeanDao = new VisitorBeanDao(visitorBeanDaoConfig, this);

        registerDao(AdvertInfo.class, advertInfoDao);
        registerDao(DepartBean.class, departBeanDao);
        registerDao(EntryInfo.class, entryInfoDao);
        registerDao(FlowInfo.class, flowInfoDao);
        registerDao(MeetInfo.class, meetInfoDao);
        registerDao(PassageBean.class, passageBeanDao);
        registerDao(UserBean.class, userBeanDao);
        registerDao(VisitorBean.class, visitorBeanDao);
    }
    
    public void clear() {
        advertInfoDaoConfig.clearIdentityScope();
        departBeanDaoConfig.clearIdentityScope();
        entryInfoDaoConfig.clearIdentityScope();
        flowInfoDaoConfig.clearIdentityScope();
        meetInfoDaoConfig.clearIdentityScope();
        passageBeanDaoConfig.clearIdentityScope();
        userBeanDaoConfig.clearIdentityScope();
        visitorBeanDaoConfig.clearIdentityScope();
    }

    public AdvertInfoDao getAdvertInfoDao() {
        return advertInfoDao;
    }

    public DepartBeanDao getDepartBeanDao() {
        return departBeanDao;
    }

    public EntryInfoDao getEntryInfoDao() {
        return entryInfoDao;
    }

    public FlowInfoDao getFlowInfoDao() {
        return flowInfoDao;
    }

    public MeetInfoDao getMeetInfoDao() {
        return meetInfoDao;
    }

    public PassageBeanDao getPassageBeanDao() {
        return passageBeanDao;
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public VisitorBeanDao getVisitorBeanDao() {
        return visitorBeanDao;
    }

}
